# примеры API-запросов

@baseUrl = http://127.0.0.1:8080

# создание user
POST  {{baseUrl}}/user/
Content-Type: application/json

{
  "name": "Yra"
}

### 

# получение user

GET  {{baseUrl}}/user/2/
Content-Type: application/json

###

# обновление user 

PATCH  {{baseUrl}}/user/2/
Content-Type: application/json

{
  "name": "Ivan_new"
}

###

# Удаление user 

DELETE  {{baseUrl}}/user/1/
Content-Type: application/json

###

# создание advertisement
POST  {{baseUrl}}/advertisement/
Content-Type: application/json

{
  "heading": "Ivan_new_1",
  "description": "11111111111",
  "user_id": 2
}

### 

# получение advertisement

GET  {{baseUrl}}/advertisement/4/
Content-Type: application/json

###

# обновление advertisement 

PATCH  {{baseUrl}}/advertisement/4/
Content-Type: application/json

{
  "heading": "1111111111111",
  "description": "11111111111111111111111",
  "user_id": 2
}

###

# Удаление advertisement 

DELETE  {{baseUrl}}/advertisement/2/
Content-Type: application/json